# Generated by Django 4.0 on 2022-01-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_sources_alter_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='column1',
            field=models.CharField(default='customer_id', max_length=30),
        ),
    ]
